# Generated by Django 5.1.1 on 2024-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
