# Generated by Django 5.1.1 on 2024-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='account_type',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_basic',
            field=models.BooleanField(default=False),
        ),
    ]
