# Generated by Django 5.1.1 on 2025-09-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
