# Generated by Django 5.1 on 2024-09-07 21:01

import core.services.file_service
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to=core.services.file_service.FileService.upload_car_photo)),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
    ]
