# Generated by Django 5.1.1 on 2025-12-29 20:34

import core.services.file_service
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('model', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('price_original', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('rate_used', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_uah', models.PositiveIntegerField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2010)])),
                ('photo_file', models.ImageField(upload_to=core.services.file_service.FileService.upload_car_photo)),
                ('photo', models.CharField(blank=True, editable=False, max_length=255)),
                ('money_currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('UAH', 'Uah')], max_length=10)),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('viewed_total', models.IntegerField(default=0)),
                ('viewed_in_day', models.IntegerField(default=0)),
                ('viewed_in_week', models.IntegerField(default=0)),
                ('viewed_in_month', models.IntegerField(default=0)),
                ('average_price_in_cities', models.IntegerField(default=0)),
                ('average_price_in_ukraine', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertisement',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AdvertisementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='advertisement.advertisementmodel')),
            ],
        ),
    ]
