# Generated by Django 5.1.1 on 2025-12-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisementmodel_rate_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='price_uah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
