# Generated by Django 5.1.1 on 2025-12-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisementmodel_price_uah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisementmodel',
            old_name='money_currency',
            new_name='currency',
        ),
    ]
