# Generated by Django 5.1.1 on 2025-12-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_rename_money_currency_advertisementmodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='edit_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisementmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('needs_edit', 'Needs Edit')], default='pending', max_length=20),
        ),
    ]
