# Generated by Django 5.1.1 on 2025-12-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_advertisementmodel_edit_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='brand',
            field=models.CharField(choices=[('BMW', 'Bmw'), ('Mercedes', 'Mercedes'), ('Ferrari', 'Ferrari'), ('Toyota', 'Toyota'), ('Audi', 'Audi')], max_length=10),
        ),
    ]
