# Generated by Django 5.1.1 on 2025-12-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisementmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='average_price_in_cities',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementmodel',
            name='average_price_in_ukraine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
